### ISSUE TITLE
DOCS: make html fails in master

### ISSUE THREAD

**Issue by michaelaye** [USGS-Astrogeology/plio#82]
(py36) └─❱❱❱ make html                                            +8978 11:04 ❰─┘
sphinx-build -b html -d build/doctrees   . build/html
Running Sphinx v1.8.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/py36/lib/python3.6/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/klay6683/miniconda3/envs/py36/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/Users/klay6683/src/plio/docs/conf.py", line 48, in <module>
    import plio
  File "/Users/klay6683/src/plio/plio/__init__.py", line 18, in <module>
    from . import io
  File "/Users/klay6683/src/plio/plio/io/__init__.py", line 25, in <module>
    from . import io_controlnetwork
  File "/Users/klay6683/src/plio/plio/io/io_controlnetwork.py", line 7, in <module>
    from plio.io import ControlNetFileV0002_pb2 as cnf
  File "/Users/klay6683/src/plio/plio/io/ControlNetFileV0002_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

make: *** [html] Error 2

**Comment by michaelaye** [comment]
This is a chained error from the missing google dependency. closing here.
